language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0

install:
    - composer install

script:
    - export PHP_CS_FIXER_IGNORE_ENV=1 && php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --diff --dry-run -v
