name: Tests

on:
    push:
    pull_request:
    schedule:
        - cron: '30 7 * * 1'

jobs:
    tests:
        if: (github.event_name == 'schedule' && github.repository == 'e-commit/csv-table-generator') || (github.event_name != 'schedule')
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   php-version: '7.2'
                        composer-flags: '--prefer-stable --prefer-lowest'
                        install-dos2unix: true
                        description: 'with lowest'
                    -   php-version: '7.2'
                        install-dos2unix: true
                    -   php-version: '7.4'
                        install-dos2unix: true
                    -   php-version: '8.0'
                        install-dos2unix: true
                    -   php-version: '8.1'
                    -   php-version: '8.0'
                        description: 'with Coding Standards'
                        coding-standards: true

        name: PHP ${{ matrix.php-version }} ${{ matrix.description }}

        runs-on: 'ubuntu-latest'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install dos2unix
                if: matrix.install-dos2unix
                run: |
                    sudo apt-get install -y dos2unix

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none
                env:
                    update: true

            -   name: Display versions
                run: |
                    php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
                    php -i

            -   name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-${{ matrix.composer-flags }}
                    restore-keys: composer-${{ runner.os }}-${{ matrix.php-version }}-

            -   name: Install dependencies
                run: composer update --no-interaction --no-progress ${{ matrix.composer-flags }}

            -   name: Run PHPUnit
                if: matrix.coding-standards != true
                run: php vendor/phpunit/phpunit/phpunit

            -   name: Run PHP CS Fixer
                if: matrix.coding-standards
                run: php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --diff --dry-run -v
